# Generated by Django 5.0 on 2024-01-05 09:39

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
