# Generated by Django 5.0 on 2024-01-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0011_remove_profile_country_alter_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='eventus', to='users.profile'),
        ),
    ]
