# Generated by Django 5.0 on 2024-01-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0003_rename_tag_ideology_alter_ideology_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='offial_logo',
            new_name='official_logo',
        ),
        migrations.AddField(
            model_name='party',
            name='acronym',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='leader',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
