# Generated by Django 5.0 on 2024-01-14 22:35

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0004_rename_offial_logo_party_official_logo_party_acronym_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
