# Generated by Django 5.0.1 on 2024-01-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0004_alter_policy_options_remove_policy_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='official_logo',
            field=models.ImageField(blank=True, default='static/images/party_logo.jpg', null=True, upload_to=''),
        ),
    ]
