# Generated by Django 5.0 on 2024-01-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0005_alter_party_country'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ideology',
            new_name='Tag',
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.RenameField(
            model_name='party',
            old_name='ideologies',
            new_name='tags',
        ),
        migrations.AddField(
            model_name='party',
            name='ideology',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
