# Generated by Django 5.0.1 on 2024-01-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0005_alter_party_official_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
