# Generated by Django 5.0.1 on 2024-01-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0006_alter_party_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='official_logo',
            field=models.ImageField(blank=True, default='/Users/bede/VoxMissa/static/imagesparty_logo.jpeg', null=True, upload_to=''),
        ),
    ]
