# Generated by Django 5.0 on 2024-01-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0006_rename_ideology_tag_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
