# Generated by Django 5.0.1 on 2024-01-24 00:42

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0007_alter_party_official_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='official_logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='party_logo.jpeg', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[100, 100], upload_to=''),
        ),
    ]
