# Generated by Django 5.0.1 on 2024-02-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0008_alter_party_official_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='acronym',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
