# Generated by Django 5.0 on 2024-01-07 03:47

import countries.models
import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='country',
            field=django_countries.fields.CountryField(countries=countries.models.G8Countries, max_length=2, null=True),
        ),
    ]
