# Generated by Django 5.0 on 2024-01-07 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='country',
        ),
    ]
