# Generated by Django 5.0 on 2024-01-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_project_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
