# Generated by Django 5.0 on 2024-01-10 20:31

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='descriptions',
        ),
        migrations.AlterField(
            model_name='project',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
