# Generated by Django 5.0 on 2024-01-17 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_remove_project_descriptions_alter_project_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='country',
        ),
    ]
