# Generated by Django 5.0.1 on 2024-01-20 00:02

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='country',
            field=models.CharField(blank=True, choices=core.utils.Africa, max_length=200, null=True),
        ),
    ]
