# Generated by Django 5.0.1 on 2024-01-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_alter_policy_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='subtopics',
            field=models.ManyToManyField(blank=True, related_name='+', to='policies.subtopic'),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
