# Generated by Django 5.0 on 2023-12-24 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_vote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['-vote_ratio', '-vote_total', 'title'], 'verbose_name_plural': 'policies'},
        ),
    ]
