# Generated by Django 5.0 on 2023-12-24 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_alter_policy_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Subtopic',
        ),
        migrations.RenameField(
            model_name='policy',
            old_name='topics',
            new_name='subtopics',
        ),
    ]
