# Generated by Django 5.0.1 on 2024-01-23 09:21

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0004_alter_policy_options_remove_policy_category_and_more'),
        ('policies', '0004_alter_policy_name_topic_alter_subtopic_policy'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.topic'),
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-vote_ratio', '-vote_total', 'name'], 'verbose_name_plural': 'policies'},
        ),
        migrations.AddField(
            model_name='topic',
            name='country',
            field=models.CharField(blank=True, choices=core.utils.Africa, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='demo_link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='topic',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='topic',
            name='source_link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='tags',
            field=models.ManyToManyField(blank=True, to='policies.tag'),
        ),
        migrations.AddField(
            model_name='topic',
            name='vote_ratio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='vote_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subtopics',
            field=models.ManyToManyField(blank=True, related_name='+', to='policies.subtopic'),
        ),
        migrations.DeleteModel(
            name='Policy',
        ),
    ]
