# Generated by Django 5.0 on 2023-12-24 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0005_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='subtopics',
        ),
        migrations.AddField(
            model_name='subtopic',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='policies.policy'),
        ),
    ]
