# Generated by Django 5.0 on 2023-12-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0006_remove_policy_subtopics_subtopic_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopic',
            name='policy',
        ),
        migrations.AddField(
            model_name='policy',
            name='subtopics',
            field=models.ManyToManyField(blank=True, to='policies.subtopic'),
        ),
    ]
