# Generated by Django 5.0.1 on 2024-01-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0006_alter_topic_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='topic',
            name='country',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='demo_link',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='source_link',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='vote_ratio',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='vote_total',
        ),
        migrations.AlterField(
            model_name='topic',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subtopics',
            field=models.ManyToManyField(to='policies.subtopic', verbose_name='list of subtopics'),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
