# Generated by Django 5.0.1 on 2024-01-24 02:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0007_alter_topic_options_remove_topic_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
