# Generated by Django 5.0.1 on 2024-01-24 06:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0008_alter_topic_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=200, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='policies.topic'),
        ),
    ]
