# Generated by Django 5.0 on 2023-12-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0008_remove_policy_subtopics_subtopic_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
