# Generated by Django 5.0.1 on 2024-01-24 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0009_alter_subtopic_id_alter_subtopic_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtopic',
            name='policy',
        ),
    ]
