# Generated by Django 5.0.1 on 2024-01-24 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0010_remove_subtopic_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='policies.topic'),
        ),
    ]
