# Generated by Django 5.0 on 2024-01-07 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0011_alter_policy_country'),
        ('users', '0011_remove_profile_country_alter_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
