# Generated by Django 5.0.1 on 2024-01-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0011_subtopic_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='subtopics',
            field=models.ManyToManyField(null=True, to='policies.subtopic', verbose_name='list of subtopics'),
        ),
    ]
