# Generated by Django 5.0.1 on 2024-01-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0012_alter_topic_subtopics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='subtopics',
            field=models.ManyToManyField(blank=True, to='policies.subtopic', verbose_name='list of subtopics'),
        ),
    ]
