# Generated by Django 5.0 on 2024-01-10 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0012_policy_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['-vote_ratio', '-vote_total', 'name'], 'verbose_name_plural': 'policies'},
        ),
        migrations.RenameField(
            model_name='policy',
            old_name='title',
            new_name='name',
        ),
    ]
