# Generated by Django 5.0.1 on 2024-01-25 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0013_alter_topic_subtopics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='policies.topic'),
        ),
    ]
