# Generated by Django 5.0.1 on 2024-01-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0014_alter_subtopic_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='tags',
            field=models.ManyToManyField(blank=True, to='policies.tag', verbose_name='list of subtopics'),
        ),
    ]
