# Generated by Django 5.0 on 2024-01-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_alter_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.TextField(null=True),
        ),
    ]
