# Generated by Django 5.0 on 2024-01-07 03:45

import countries.models
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_country_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(countries=countries.models.G8Countries, max_length=2)),
                ('approve', models.BooleanField()),
            ],
        ),
    ]
