# Generated by Django 5.0 on 2024-01-14 21:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0005_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='party',
            field=models.ManyToManyField(blank=True, to='countries.party'),
        ),
    ]
