name: Add issues to release testing project

on:
  issues:
    types:
      - opened
# on: workflow_dispatch
jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        id: addItem
        with:
          project-url: https://github.com/users/ngaruko/projects/2/views/1
          github-token: ${{ secrets.GH_TOKEN }}
          labeled: release, bug
          label-operator: OR

      - uses: kalgurn/update-project-item-status@main
        with:
          project-url: https://github.com/users/ngaruko/projects/2/views/1
          github-token: ${{ secrets.GH_TOKEN }}
          item-id: ${{ steps.addItem.outputs.itemId }}
          # item-id: '2164533376'
          status: "Todo"
